import { MigrationInterface, QueryRunner } from "typeorm";

export class InitTable1766745517687 implements MigrationInterface {
    name = 'InitTable1766745517687'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`notification_details\` (\`id\` int NOT NULL AUTO_INCREMENT, \`notificationId\` int NOT NULL, \`entityRefId\` varchar(36) NULL, \`userId\` int NOT NULL, \`seen\` tinyint NOT NULL DEFAULT 0, \`seenAt\` datetime NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`notifications\` (\`id\` int NOT NULL AUTO_INCREMENT, \`title\` varchar(2000) NOT NULL, \`body\` text NULL, \`receiverType\` int NOT NULL DEFAULT '2', \`category\` int NOT NULL DEFAULT '2', \`receivers\` json NOT NULL, \`creatorId\` int NOT NULL, \`redirectType\` enum ('application', 'shift-assignment', 'finance-external', 'finance-internal', 'user-device') NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` int NOT NULL AUTO_INCREMENT, \`email\` varchar(200) NOT NULL COMMENT 'Email của người dùng', \`password\` varchar(200) NOT NULL COMMENT 'Mật khẩu của người dùng', \`fullName\` varchar(200) NOT NULL COMMENT 'Họ và tên đầy đủ của người dùng', \`avatar\` varchar(200) NULL COMMENT 'Đường dẫn ảnh đại diện', \`roleId\` int NULL, \`phoneNumber\` varchar(15) NULL COMMENT 'Số điện thoại liên hệ', \`address\` varchar(500) NULL COMMENT 'Địa chỉ người dùng', \`status\` tinyint NOT NULL COMMENT 'Trạng thái' DEFAULT '1', \`lastRequireLogoutAt\` datetime NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`products\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL COMMENT 'Tên sản phẩm', \`slug\` varchar(255) NOT NULL COMMENT 'Đường dẫn URL của sản phẩm', \`sku\` varchar(50) NOT NULL COMMENT 'Mã SKU sản phẩm', \`shortDescription\` varchar(500) NULL COMMENT 'Mô tả ngắn', \`description\` longtext NULL COMMENT 'Mô tả chi tiết (HTML)', \`price\` decimal(15,2) NOT NULL COMMENT 'Giá gốc' DEFAULT '0.00', \`salePrice\` decimal(15,2) NULL COMMENT 'Giá khuyến mãi', \`costPrice\` decimal(15,2) NOT NULL COMMENT 'Giá vốn' DEFAULT '0.00', \`stockQuantity\` int NOT NULL COMMENT 'Số lượng tồn kho' DEFAULT '0', \`unit\` varchar(50) NULL COMMENT 'Đơn vị tính (cái, hộp, kg...)', \`weight\` decimal(10,2) NULL COMMENT 'Trọng lượng (kg)', \`length\` decimal(10,2) NULL COMMENT 'Chiều dài (cm)', \`width\` decimal(10,2) NULL COMMENT 'Chiều rộng (cm)', \`height\` decimal(10,2) NULL COMMENT 'Chiều cao (cm)', \`thumbnailUrl\` varchar(500) NULL COMMENT 'Ảnh đại diện chính', \`images\` json NULL COMMENT 'Danh sách ảnh sản phẩm', \`brand\` varchar(255) NULL COMMENT 'Thương hiệu', \`origin\` varchar(255) NULL COMMENT 'Xuất xứ', \`barcode\` varchar(100) NULL COMMENT 'Mã vạch (Barcode)', \`priority\` int NOT NULL COMMENT 'Độ ưu tiên hiển thị' DEFAULT '0', \`viewCount\` int NOT NULL COMMENT 'Lượt xem' DEFAULT '0', \`soldCount\` int NOT NULL COMMENT 'Số lượng đã bán' DEFAULT '0', \`averageRating\` decimal(3,2) NOT NULL COMMENT 'Đánh giá trung bình (0-5)' DEFAULT '0.00', \`reviewCount\` int NOT NULL COMMENT 'Số lượng đánh giá' DEFAULT '0', \`isFeatured\` tinyint NOT NULL COMMENT 'Sản phẩm nổi bật' DEFAULT 0, \`isNew\` tinyint NOT NULL COMMENT 'Sản phẩm mới' DEFAULT 0, \`isBestSeller\` tinyint NOT NULL COMMENT 'Best seller' DEFAULT 0, \`attributes\` json NULL COMMENT 'Thuộc tính sản phẩm (màu sắc, kích thước...)', \`specifications\` json NULL COMMENT 'Thông số kỹ thuật', \`metaTitle\` varchar(255) NULL COMMENT 'Meta title cho SEO', \`metaDescription\` text NULL COMMENT 'Meta description cho SEO', \`metaKeywords\` varchar(500) NULL COMMENT 'SEO keywords', \`metaRobots\` varchar(50) NOT NULL COMMENT 'Meta robots' DEFAULT 'index,follow', \`canonicalUrl\` varchar(500) NULL COMMENT 'Full URL chính thức (cho duplicate content)', \`seoBaseSchema\` json NULL COMMENT 'Schema.org cho product', \`status\` tinyint NOT NULL COMMENT 'Trạng thái bật tắt' DEFAULT '1', \`deleted\` tinyint NOT NULL COMMENT 'Trạng thái xóa' DEFAULT '0', \`createdBy\` int NULL COMMENT 'ID người tạo', \`updatedBy\` int NULL COMMENT 'ID người cập nhật', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_464f927ae360106b783ed0b410\` (\`slug\`), UNIQUE INDEX \`IDX_c44ac33a05b144dd0d9ddcf932\` (\`sku\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`categories\` (\`id\` int NOT NULL AUTO_INCREMENT, \`parentId\` int NULL COMMENT 'ID CHA', \`name\` varchar(255) NOT NULL COMMENT 'Tên danh mục', \`slug\` varchar(255) NOT NULL COMMENT 'địa chỉ url của cate', \`description\` longtext NULL COMMENT 'content html', \`idPath\` varchar(500) NOT NULL COMMENT 'đường dẫn của danh mục' DEFAULT '', \`priority\` int NOT NULL COMMENT 'độ ưu tiên hiển thị' DEFAULT '0', \`iconUrl\` varchar(500) NULL COMMENT 'icon hiển thị cate', \`thumbnailUrl\` varchar(500) NULL COMMENT 'ảnh đại diện của cate', \`canonicalUrl\` varchar(500) NULL COMMENT 'Full URL chính thức (cho duplicate content)', \`level\` int NOT NULL COMMENT 'level của cate level 0 thường sẽ là cate cha' DEFAULT '0', \`metaTitle\` varchar(255) NULL, \`metaDescription\` text NULL, \`metaKeywords\` varchar(500) NULL COMMENT 'SEO keywords', \`metaRobots\` varchar(50) NOT NULL COMMENT 'index,follow' DEFAULT 'noindex,nofollow', \`seoBaseSchema\` json NULL COMMENT 'Schema.org cho category', \`status\` tinyint NOT NULL COMMENT 'Trạng thái bật tắt' DEFAULT '1', \`deleted\` tinyint NOT NULL COMMENT 'Trạng thái xóa' DEFAULT '0', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_420d9f679d41281f282f5bc7d0\` (\`slug\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`product_categories\` (\`id\` int NOT NULL AUTO_INCREMENT, \`productId\` int NOT NULL COMMENT 'ID sản phẩm', \`categoryId\` int NOT NULL COMMENT 'ID danh mục', \`isPrimary\` tinyint NOT NULL COMMENT 'Đánh dấu danh mục chính' DEFAULT 0, \`displayOrder\` int NOT NULL COMMENT 'Thứ tự hiển thị trong danh mục' DEFAULT '0', \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_e65c1adebf00d61f1c84a4f395\` (\`productId\`, \`categoryId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cart_items\` (\`id\` int NOT NULL AUTO_INCREMENT, \`cartId\` int NOT NULL COMMENT 'ID giỏ hàng', \`productId\` int NOT NULL COMMENT 'ID sản phẩm', \`quantity\` int NOT NULL COMMENT 'Số lượng' DEFAULT '1', \`price\` decimal(15,2) NOT NULL COMMENT 'Giá tại thời điểm thêm vào giỏ', \`totalPrice\` decimal(15,2) NOT NULL COMMENT 'Tổng tiền (quantity * price)' DEFAULT '0.00', \`selectedAttributes\` json NULL COMMENT 'Thuộc tính đã chọn (màu sắc, size...)', \`note\` text NULL COMMENT 'Ghi chú cho sản phẩm', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_2bf7996b7946ce753b60a87468\` (\`cartId\`, \`productId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`carts\` (\`id\` int NOT NULL AUTO_INCREMENT, \`totalAmount\` decimal(15,2) NOT NULL COMMENT 'Tổng tiền' DEFAULT '0.00', \`totalItems\` int NOT NULL COMMENT 'Tổng số sản phẩm' DEFAULT '0', \`status\` tinyint NOT NULL COMMENT 'Trạng thái giỏ hàng' DEFAULT '1', \`note\` text NULL COMMENT 'Ghi chú', \`expiresAt\` datetime NULL COMMENT 'Thời gian hết hạn giỏ hàng', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE \`carts\``);
        await queryRunner.query(`DROP INDEX \`IDX_2bf7996b7946ce753b60a87468\` ON \`cart_items\``);
        await queryRunner.query(`DROP TABLE \`cart_items\``);
        await queryRunner.query(`DROP INDEX \`IDX_e65c1adebf00d61f1c84a4f395\` ON \`product_categories\``);
        await queryRunner.query(`DROP TABLE \`product_categories\``);
        await queryRunner.query(`DROP INDEX \`IDX_420d9f679d41281f282f5bc7d0\` ON \`categories\``);
        await queryRunner.query(`DROP TABLE \`categories\``);
        await queryRunner.query(`DROP INDEX \`IDX_c44ac33a05b144dd0d9ddcf932\` ON \`products\``);
        await queryRunner.query(`DROP INDEX \`IDX_464f927ae360106b783ed0b410\` ON \`products\``);
        await queryRunner.query(`DROP TABLE \`products\``);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP TABLE \`notifications\``);
        await queryRunner.query(`DROP TABLE \`notification_details\``);
    }

}
