export enum OverviewTypeEnum {
  FUEL_ALLOCATION = 'FUEL_ALLOCATION',
  MATERIAL_SUPPLY = 'MATERIAL_SUPPLY',
  EQUIPMENT_SUPPLY = 'EQUIPMENT_SUPPLY',
  WORKER_SUPPLY = 'WORKER_SUPPLY',
  CONSTRUCTION_PROGRESS = 'CONSTRUCTION_PROGRESS',
  FINANCIAL_SUMMARY = 'FINANCIAL_SUMMARY',
  ATTENDANCE_SUMMARY = 'ATTENDANCE_SUMMARY',
  // Có thể thêm các loại khác trong tương lai
}
