export enum PermissionEnum {
  /** Affiliate */
  AFFILIATE_VIEW = 'AFFILIATE_VIEW',
  AFFILIATE_EXPORT = 'AFFILIATE_EXPORT',
  AFFILIATE_CREATE = 'AFFILIATE_CREATE',
  AFFILIATE_UPDATE = 'AFFILIATE_UPDATE',

  /** User */
  USER_VIEW = 'USER_VIEW',
  USER_EXPORT = 'USER_EXPORT',
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',

  /** Role */
  ROLE_VIEW = 'ROLE_VIEW',
  ROLE_EXPORT = 'ROLE_EXPORT',
  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_UPDATE = 'ROLE_UPDATE',
}
